### ISSUE TITLE
请问这个滑稽您是从哪里找的

### ISSUE THREAD

**Issue by lonr** [YunTM/huaji#1]
这个滑稽是我目前能找到最高清的了

**Comment by Lensual** [comment]
我也忘了哪里找到的了…某qq群共享？

**Comment by lonr** [comment]
总之，谢谢你的滑稽 :smirk:

**Comment by Lensual** [comment]
啊我找到了
来自telegram泡泡表情

@lonr 

![tim 20170911210427](https://user-images.githubusercontent.com/11309551/30275776-015876fc-9735-11e7-959e-4b7a5f2f3ff6.png)

**Comment by lonr** [comment]
https://t.me/addstickers/PaopaoHD

**Comment by Lensual** [comment]
THX
